#pragma once
#include "Problem 20-Valid Parentheses/Solution20.h"
#include "Problem 21-Merge Two Sorted Lists/Solution21.h"
#include "Problem 22-Generate Parentheses/Solution22.h"
#include "Problem 23-Merge k Sorted Lists/Solution23.h"
#include "Problem 24-Swap Nodes in Pairs/Solution24.h"
#include "Problem 25-Reverse Nodes in k-Group/Solution25.h"
#include "Problem 26-Remove Duplicates from Sorted Array/Solution26.h"
#include "Problem 27-Remove Element/Solution27.h"
#include "Problem 28-Implement strStr/Solution28.h"
#include "Problem 29-Divide Two Integers/Solution29.h"
#include "Problem 30-Substring with Concatenation of All Words/Solution30.h"
#include "Problem 31-Next Permutation/Solution31.h"
#include "Problem 32-Longest Valid Parentheses/Solution32.h"
#include "Problem 33-Search in Rotated Sorted Array/Solution33.h"
#include "Problem 34-Find First and Last Position of Element in Sorted Array/Solution34.h"
#include "Problem 35-Search Insert Position/Solution35.h"
#include "Problem 36-Valid Sudoku/Solution36.h"
#include "Problem 37-Sudoku Solver/Solution37.h"
#include "Problem 38-Count and Say/Solution38.h"
#include "Problem 39-Combination Sum/Solution39.h"
#include "Problem 40-Combination Sum II/Solution40.h"
#include "Problem 41-First Missing Positive/Solution41.h"
#include "Problem 42-Trapping Rain Water/Solution42.h"
#include "Problem 43-Multiply Strings/Solution43.h"
#include "Problem 44-Wildcard Matching/Solution44.h"
#include "Problem 45-Jump Game II/Solution45.h"
#include "Problem 46-Permutations/Solution46.h"
#include "Problem 47-Permutations II/Solution47.h"
#include "Problem 48-Rotate Image/Solution48.h"
#include "Problem 49-Group Anagrams/Solution49.h"
#include "Problem 50-Pow(x, n)/Solution50.h"
#include "Problem 51-N-Queens/Solution51.h"
#include "Problem 52-N-Queens II/Solution52.h"
#include "Problem 53-Maximum Subarray/Solution53.h"
#include "Problem 54-Spiral Matrix/Solution54.h"
#include "Problem 55-Jump Game/Solution55.h"
#include "Problem 56-Merge Intervals/Solution56.h"
#include "Problem 75-Sort Colors/Solution75.h"
#include "Problem 94-Binary Tree Inorder Traversal/Solution94.h"
#include "Problem 95-Unique Binary Search Trees II/Solution95.h"
#include "Problem 96-Unique Binary Search Trees/Solution96.h"
#include "Problem 100-Same Tree/Solution100.h"
