#pragma once
#include "Problem 20-Valid Parentheses/Solution20.h"
#include "Problem 21-Merge Two Sorted Lists/Solution21.h"
#include "Problem 22-Generate Parentheses/Solution22.h"
#include "Problem 23-Merge k Sorted Lists/Solution23.h"
#include "Problem 24-Swap Nodes in Pairs/Solution24.h"
#include "Problem 25-Reverse Nodes in k-Group/Solution25.h"
#include "Problem 26-Remove Duplicates from Sorted Array/Solution26.h"
#include "Problem 27-Remove Element/Solution27.h"
#include "Problem 28-Implement strStr/Solution28.h"
#include "Problem 29-Divide Two Integers/Solution29.h"
#include "Problem 30-Substring with Concatenation of All Words/Solution30.h"
#include "Problem 31-Next Permutation/Solution31.h"
#include "Problem 32-Longest Valid Parentheses/Solution32.h"
#include "Problem 33-Search in Rotated Sorted Array/Solution33.h"
#include "Problem 34-Find First and Last Position of Element in Sorted Array/Solution34.h"
#include "Problem 35-Search Insert Position/Solution35.h"
#include "Problem 36-Valid Sudoku/Solution36.h"
#include "Problem 38-Count and Say/Solution38.h"
#include "Problem 39-Combination Sum/Solution39.h"
